"""Initial

Revision ID: 4cdff6198f45
Revises: 3adcc9a56557
Create Date: 2022-10-28 12:25:34.132138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdff6198f45'
down_revision = '3adcc9a56557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
