"""Add img

Revision ID: 9c4057b9a8a3
Revises: 4cdff6198f45
Create Date: 2023-05-01 11:45:39.945794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4057b9a8a3'
down_revision = '4cdff6198f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Event', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Event', 'image')
    # ### end Alembic commands ###
